services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: mydb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_reviews_platform
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
