services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "mydb"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "book-review-platform"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://mydb:password@db:5432/book-review-platform
