# Railway Backend Configuration

# Build Configuration
[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

# Start Command (handled by Dockerfile)
[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300

# Environment Variables
[env]
NODE_ENV = "production"
